from app.extensions import db
from app.models.hospital import Hospital


NEW_HOSPITALS = [

    # ══════════════════════════════════════════════════════════════
    # KERALA — HOSPITALS & NEUROLOGY CENTRES
    # ══════════════════════════════════════════════════════════════

    {
        'name': 'Amrita Institute of Medical Sciences',
        'address': 'AIMS Ponekkara P.O., Edappally',
        'city': 'Kochi',
        'state': 'Kerala',
        'phone': '+91 484 280 1234',
        'email': 'info@aims.amrita.edu',
        'website': 'https://www.aims.amrita.edu',
        'specialty': 'Neurosurgery',
        'hospital_type': 'Private',
        'accreditation': 'NABH, NABL',
        'rating': 4.8,
        'facilities': 'Brain Tumor Surgery,Gamma Knife,Neuro ICU,3T MRI,PET-CT,Radiation Therapy,Neuronavigation',
        'doctors': 'Dr. Mathew Abraham – Neurosurgeon, Dr. Anand Kumar – Neuro Oncologist',
        'is_mri_center': True,
        'mri_types': '3T MRI, fMRI, MR Spectroscopy',
        'cost_range': '₹5000 – ₹12000',
        'latitude': 10.0261,
        'longitude': 76.3083,
        'is_active': True,
    },
    {
        'name': 'VPS Lakeshore Hospital',
        'address': 'NH 47 - Bye Pass Road, Nettoor P.O., Maradu',
        'city': 'Kochi',
        'state': 'Kerala',
        'phone': '+91 484 270 2288',
        'email': 'info@lakeshorehospital.com',
        'website': 'https://www.lakeshorehospital.com',
        'specialty': 'Neurology',
        'hospital_type': 'Private',
        'accreditation': 'NABH',
        'rating': 4.6,
        'facilities': 'Brain Tumor Surgery,Neuro ICU,3T MRI,CT Scan,Neuronavigation,Spine Surgery',
        'doctors': 'Dr. Suresh Nair – Neurologist, Dr. Rajan Menon – Neurosurgeon',
        'is_mri_center': True,
        'mri_types': '3T MRI, Open MRI',
        'cost_range': '₹4500 – ₹10000',
        'latitude': 9.9526,
        'longitude': 76.3085,
        'is_active': True,
    },
    {
        'name': 'Meitra Hospital',
        'address': 'Building No. 38/2208-B, Karaparamba–Kunduparamba, Mini Bypass Road, Edakkad',
        'city': 'Kozhikode',
        'state': 'Kerala',
        'phone': '+91 495 304 0000',
        'email': 'info@meitra.com',
        'website': 'https://www.meitra.com',
        'specialty': 'Neurology',
        'hospital_type': 'Private',
        'accreditation': 'NABH',
        'rating': 4.5,
        'facilities': 'Brain Tumor Surgery,Neuro ICU,MRI,CT Scan,Epilepsy Clinic,Stroke Unit',
        'doctors': 'Dr. Anoop Ayyappan – Neurosurgeon, Dr. Pradeep Kumar – Neurologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI, 3T MRI',
        'cost_range': '₹4000 – ₹9000',
        'latitude': 11.2742,
        'longitude': 75.8217,
        'is_active': True,
    },
    {
        'name': 'Government Medical College Hospital Thrissur',
        'address': 'Mulankunnathu Kavu, Medical College P.O.',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 487 236 1200',
        'email': 'gmctsr@kerala.gov.in',
        'website': 'https://dme.kerala.gov.in',
        'specialty': 'Neurology',
        'hospital_type': 'Public',
        'accreditation': 'NABH',
        'rating': 4.1,
        'facilities': 'Brain Tumor Surgery,Neuro ICU,MRI,CT Scan,Neurology OPD,Emergency Neurology',
        'doctors': 'Dr. P. Suresh Kumar – Head of Neurosurgery, Dr. Sreeja – Neurologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹500 – ₹2500',
        'latitude': 10.5276,
        'longitude': 76.2144,
        'is_active': True,
    },
    {
        'name': 'Jubilee Mission Medical College & Research Institute',
        'address': 'P.B. No. 737, Jubilee Mission P.O.',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 487 242 4400',
        'email': 'info@jubileemission.org',
        'website': 'https://www.jubileemissionhospital.org',
        'specialty': 'Neurosurgery',
        'hospital_type': 'Private',
        'accreditation': 'NABH',
        'rating': 4.4,
        'facilities': 'Brain Tumor Surgery,MRI,CT Scan,Neuro ICU,Physiotherapy,Rehabilitation',
        'doctors': 'Dr. George Vilanilam – Neurosurgeon, Dr. Shaji – Neurologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹3000 – ₹7000',
        'latitude': 10.5190,
        'longitude': 76.2110,
        'is_active': True,
    },
    {
        'name': 'Westfort Hi-Tech Hospital',
        'address': 'Westfort Junction, Thrissur–Palakkad NH',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 487 244 3000',
        'email': 'info@westforthitech.com',
        'website': 'https://www.westforthitech.com',
        'specialty': 'Neurology',
        'hospital_type': 'Private',
        'accreditation': 'NABH',
        'rating': 4.3,
        'facilities': 'Neurology,MRI,CT Scan,Stroke Unit,Neuro ICU',
        'doctors': 'Dr. Rajesh Nair – Neurologist, Dr. Ajith Menon – Neurosurgeon',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹3000 – ₹7000',
        'latitude': 10.5320,
        'longitude': 76.2200,
        'is_active': True,
    },
    {
        'name': 'Government Medical College Hospital Kozhikode',
        'address': 'Medical College P.O.',
        'city': 'Kozhikode',
        'state': 'Kerala',
        'phone': '+91 495 235 0216',
        'email': 'principalmck@kerala.gov.in',
        'website': 'https://dme.kerala.gov.in',
        'specialty': 'Neurology',
        'hospital_type': 'Public',
        'accreditation': 'NABH',
        'rating': 4.0,
        'facilities': 'Brain Tumor Surgery,MRI,CT Scan,Neuro ICU,Radiation Therapy,Neurology OPD',
        'doctors': 'Dr. Suresh Kumar – Professor Neurosurgery, Dr. Anitha – Neurologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹400 – ₹2000',
        'latitude': 11.2554,
        'longitude': 75.7979,
        'is_active': True,
    },
    {
        'name': 'SCTIMST — Sree Chitra Tirunal Institute',
        'address': 'Medical Technology Complex, Poojapura',
        'city': 'Thiruvananthapuram',
        'state': 'Kerala',
        'phone': '+91 471 252 4141',
        'email': 'contact@sctimst.ac.in',
        'website': 'https://www.sctimst.ac.in',
        'specialty': 'Neuro Oncology',
        'hospital_type': 'Public',
        'accreditation': 'NABH, NABL',
        'rating': 4.8,
        'facilities': 'Brain Tumor Surgery,Gamma Knife,Neuro ICU,3T MRI,PET-CT,Cyberknife,Neuronavigation,Interventional Neuroradiology',
        'doctors': 'Dr. Suresh Nair – Director, Dr. Krishnakumar – Neurosurgeon, Dr. Anita – Neuro Oncologist',
        'is_mri_center': True,
        'mri_types': '3T MRI, fMRI, MR Spectroscopy, Intraoperative MRI',
        'cost_range': '₹1000 – ₹5000',
        'latitude': 8.5440,
        'longitude': 76.9430,
        'is_active': True,
    },
    {
        'name': 'Government Medical College Thiruvananthapuram',
        'address': 'Medical College Campus, Ulloor',
        'city': 'Thiruvananthapuram',
        'state': 'Kerala',
        'phone': '+91 471 244 3152',
        'email': 'mctvm@kerala.gov.in',
        'website': 'https://dme.kerala.gov.in',
        'specialty': 'Neurology',
        'hospital_type': 'Public',
        'accreditation': 'NABH',
        'rating': 4.0,
        'facilities': 'Brain Tumor Surgery,MRI,CT Scan,Neuro ICU,Neurology OPD',
        'doctors': 'Dr. Anil Kumar – Professor Neurology, Dr. Rema – Neurosurgeon',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹300 – ₹2000',
        'latitude': 8.5241,
        'longitude': 76.9366,
        'is_active': True,
    },
    {
        'name': 'Aster MIMS Hospital',
        'address': 'Govindapuram P.O., Kozhikode–Mavoor Road',
        'city': 'Kozhikode',
        'state': 'Kerala',
        'phone': '+91 495 304 5000',
        'email': 'info@astermims.com',
        'website': 'https://www.astermims.com',
        'specialty': 'Neurology',
        'hospital_type': 'Private',
        'accreditation': 'NABH, JCI',
        'rating': 4.5,
        'facilities': 'Brain Tumor Surgery,Neuro ICU,3T MRI,CT Scan,Stroke Unit,Gamma Knife,Neuronavigation',
        'doctors': 'Dr. P.N. Sylaja – Neurologist, Dr. Harikrishnan – Neurosurgeon',
        'is_mri_center': True,
        'mri_types': '3T MRI, 1.5T MRI',
        'cost_range': '₹4500 – ₹11000',
        'latitude': 11.2784,
        'longitude': 75.8107,
        'is_active': True,
    },
    {
        'name': 'Baby Memorial Hospital',
        'address': 'Indira Gandhi Road',
        'city': 'Kozhikode',
        'state': 'Kerala',
        'phone': '+91 495 276 6000',
        'email': 'info@babymemorial.com',
        'website': 'https://www.babymemorial.com',
        'specialty': 'Neurology',
        'hospital_type': 'Private',
        'accreditation': 'NABH',
        'rating': 4.3,
        'facilities': 'Neurology,MRI,CT Scan,Neuro ICU,Stroke Unit,Epilepsy Clinic',
        'doctors': 'Dr. Sajith – Neurologist, Dr. Pradeep – Neurosurgeon',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹3500 – ₹8000',
        'latitude': 11.2496,
        'longitude': 75.7741,
        'is_active': True,
    },
    {
        'name': 'PVS Memorial Hospital',
        'address': 'NH 544, Kaloor',
        'city': 'Kochi',
        'state': 'Kerala',
        'phone': '+91 484 234 5555',
        'email': 'info@pvsmemorial.com',
        'website': 'https://www.pvsmemorial.com',
        'specialty': 'Neurology',
        'hospital_type': 'Private',
        'accreditation': 'NABH',
        'rating': 4.2,
        'facilities': 'Neurology,MRI,CT Scan,Neuro ICU,Brain Tumor Surgery',
        'doctors': 'Dr. Rajiv Antony – Neurosurgeon, Dr. Bindhu – Neurologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹3500 – ₹8000',
        'latitude': 9.9927,
        'longitude': 76.2913,
        'is_active': True,
    },

    # ══════════════════════════════════════════════════════════════
    # KERALA — MRI SCAN CENTRES (standalone diagnostic)
    # ══════════════════════════════════════════════════════════════

    {
        'name': 'Elite Scanning Centre',
        'address': 'Koorkkanchery, Thrissur–Guruvayur Road',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 487 235 0000',
        'email': 'info@elitescancentre.com',
        'website': 'https://elitescancentre.com',
        'specialty': 'Radiology',
        'hospital_type': 'Clinic',
        'accreditation': 'NABL',
        'rating': 4.6,
        'facilities': 'MRI,CT Scan,Ultrasound,X-Ray,4D Ultrasound,AI-Powered Imaging',
        'doctors': 'Dr. Binu Joseph – Radiologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI, AI-assisted MRI',
        'cost_range': '₹2500 – ₹6000',
        'latitude': 10.5510,
        'longitude': 76.2020,
        'is_active': True,
    },
    {
        'name': 'Vita Diagnostics',
        'address': 'Near Medical College, Ollur Road',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 487 232 3780',
        'email': 'vitadiagnostics@gmail.com',
        'website': 'https://vitadiagnostics.org',
        'specialty': 'Radiology',
        'hospital_type': 'Clinic',
        'accreditation': 'NABL',
        'rating': 4.4,
        'facilities': 'MRI,CT Scan,Ultrasound,X-Ray,Mammography',
        'doctors': 'Dr. Sajan – Radiologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI (Signa HDxt 28)',
        'cost_range': '₹2500 – ₹5500',
        'latitude': 10.5250,
        'longitude': 76.2130,
        'is_active': True,
    },
    {
        'name': 'Magnus Diagnostics',
        'address': 'Near Thrissur Round, Poothole Road',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 890 310 1010',
        'email': 'info@magnusdiagnostics.in',
        'website': 'https://magnusdiagnostics.in',
        'specialty': 'Radiology',
        'hospital_type': 'Clinic',
        'accreditation': 'NABL',
        'rating': 4.7,
        'facilities': 'MRI,CT Scan,Ultrasound,X-Ray,Pathology Lab',
        'doctors': 'Dr. Aneesh – Radiologist',
        'is_mri_center': True,
        'mri_types': '3T MRI, Open MRI',
        'cost_range': '₹3000 – ₹7000',
        'latitude': 10.5290,
        'longitude': 76.2180,
        'is_active': True,
    },
    {
        'name': 'Hindlabs MRI & CT Scan Centre — Thrissur',
        'address': 'Radiology Block, Govt Medical College Hospital, Mulankunnathu',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 487 236 1200',
        'email': 'thrissur@hindlabs.in',
        'website': 'https://hindlabs.in/hindlabs-thrissur',
        'specialty': 'Radiology',
        'hospital_type': 'Public',
        'accreditation': 'NABL',
        'rating': 4.0,
        'facilities': 'MRI,CT Scan,X-Ray,Ultrasound',
        'doctors': 'Radiology Team',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹1500 – ₹4000',
        'latitude': 10.5276,
        'longitude': 76.2144,
        'is_active': True,
    },
    {
        'name': 'Mediscan Centre — Thrissur',
        'address': 'Round South, Near SBI Main Branch',
        'city': 'Thrissur',
        'state': 'Kerala',
        'phone': '+91 487 232 0000',
        'email': 'info@mediscan.in',
        'website': 'https://www.mediscan.in',
        'specialty': 'Radiology',
        'hospital_type': 'Clinic',
        'accreditation': 'NABL',
        'rating': 4.3,
        'facilities': 'MRI,CT Scan,Ultrasound,X-Ray,Mammography,Lab Tests',
        'doctors': 'Dr. Abraham Sebastian – Radiologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹2500 – ₹5500',
        'latitude': 10.5268,
        'longitude': 76.2144,
        'is_active': True,
    },
    {
        'name': 'Hindlabs MRI & CT Scan Centre — Kozhikode',
        'address': 'Ground Floor, Super Speciality Block, Govt Medical College',
        'city': 'Kozhikode',
        'state': 'Kerala',
        'phone': '+91 495 235 0216',
        'email': 'kozhikode@hindlabs.in',
        'website': 'https://hindlabs.in/hindlabs-kozhikode',
        'specialty': 'Radiology',
        'hospital_type': 'Public',
        'accreditation': 'NABL',
        'rating': 4.0,
        'facilities': 'MRI,CT Scan,X-Ray,Ultrasound',
        'doctors': 'Radiology Team',
        'is_mri_center': True,
        'mri_types': '1.5T MRI',
        'cost_range': '₹1200 – ₹3500',
        'latitude': 11.2554,
        'longitude': 75.7979,
        'is_active': True,
    },
    {
        'name': 'Travancore Scans & Laboratory',
        'address': "Oommens' Building, Pazhaya Road, Medical College P.O.",
        'city': 'Thiruvananthapuram',
        'state': 'Kerala',
        'phone': '+91 471 244 1070',
        'email': 'info@travancorescans.in',
        'website': 'https://travancorescans.in',
        'specialty': 'Radiology',
        'hospital_type': 'Clinic',
        'accreditation': 'NABL',
        'rating': 4.3,
        'facilities': 'MRI,CT Scan,Ultrasound,X-Ray,Lab Tests',
        'doctors': 'Dr. Reji – Radiologist',
        'is_mri_center': True,
        'mri_types': '1.5T MRI, Multislice CT',
        'cost_range': '₹2000 – ₹5000',
        'latitude': 8.5289,
        'longitude': 76.9320,
        'is_active': True,
    },

    # ══════════════════════════════════════════════════════════════
    # INDIA — TOP NEUROLOGY / BRAIN TUMOUR HOSPITALS
    # ══════════════════════════════════════════════════════════════

    {
        'name': 'NIMHANS',
        'address': 'Hosur Road, Lakkasandra',
        'city': 'Bangalore',
        'state': 'Karnataka',
        'phone': '+91 80 2699 5000',
        'email': 'nimhans@nimhans.ac.in',
        'website': 'https://www.nimhans.ac.in',
        'specialty': 'Neuro Oncology',
        'hospital_type': 'Public',
        'accreditation': 'NABH',
        'rating': 4.9,
        'facilities': 'Brain Tumor Surgery,Neuro ICU,3T MRI,PET-CT,Gamma Knife,Neuropsychiatry,Neurorehabilitation',
        'doctors': 'Dr. Dhananjaya Bhat – Neurosurgeon, Dr. Bhaskara – Neuro Oncologist',
        'is_mri_center': True,
        'mri_types': '3T MRI, fMRI, MR Spectroscopy',
        'cost_range': '₹1000 – ₹5000',
        'latitude': 12.9429,
        'longitude': 77.5954,
        'is_active': True,
    },
    {
        'name': 'Apollo Hospitals — Chennai',
        'address': '21, Greams Lane, Off Greams Road',
        'city': 'Chennai',
        'state': 'Tamil Nadu',
        'phone': '+91 44 2829 3333',
        'email': 'apollo@apollohospitals.com',
        'website': 'https://www.apollohospitals.com',
        'specialty': 'Neuro Oncology',
        'hospital_type': 'Private',
        'accreditation': 'NABH, JCI',
        'rating': 4.8,
        'facilities': 'Brain Tumor Surgery,Gamma Knife,Cyberknife,Neuro ICU,3T MRI,PET-CT,Intraoperative MRI,Neuronavigation',
        'doctors': 'Dr. Ramesh Babu – Neurosurgeon, Dr. Suresh – Neuro Oncologist',
        'is_mri_center': True,
        'mri_types': '3T MRI, Intraoperative MRI',
        'cost_range': '₹6000 – ₹15000',
        'latitude': 13.0569,
        'longitude': 80.2530,
        'is_active': True,
    },
    {
        'name': 'Kokilaben Dhirubhai Ambani Hospital',
        'address': 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows',
        'city': 'Mumbai',
        'state': 'Maharashtra',
        'phone': '+91 22 3066 9999',
        'email': 'info@kokilabenhospital.com',
        'website': 'https://www.kokilabenhospital.com',
        'specialty': 'Neuro Oncology',
        'hospital_type': 'Private',
        'accreditation': 'NABH, JCI',
        'rating': 4.8,
        'facilities': 'Brain Tumor Surgery,Intraoperative MRI (IMRIS),Gamma Knife,Neuro ICU,3T MRI,PET-CT,Robotic Surgery',
        'doctors': 'Dr. Abhijit Pawar – Neurosurgeon, Dr. Rakesh Jalali – Radiation Oncologist',
        'is_mri_center': True,
        'mri_types': '3T MRI, Intraoperative MRI (IMRIS)',
        'cost_range': '₹8000 – ₹18000',
        'latitude': 19.1308,
        'longitude': 72.8279,
        'is_active': True,
    },
    {
        'name': 'AIIMS New Delhi',
        'address': 'Sri Aurobindo Marg, Ansari Nagar',
        'city': 'New Delhi',
        'state': 'Delhi',
        'phone': '+91 11 2658 8500',
        'email': 'director@aiims.ac.in',
        'website': 'https://www.aiims.edu',
        'specialty': 'Neuro Oncology',
        'hospital_type': 'Public',
        'accreditation': 'NABH',
        'rating': 4.9,
        'facilities': 'Brain Tumor Surgery,Gamma Knife,Neuro ICU,3T MRI,PET-CT,fMRI,Neurosurgical Robotics,CyberKnife',
        'doctors': 'Dr. P. Sarat Chandra – Neurosurgeon, Dr. Manmohan Singh – Neurosurgeon',
        'is_mri_center': True,
        'mri_types': '3T MRI, fMRI, MR Spectroscopy',
        'cost_range': '₹500 – ₹4000',
        'latitude': 28.5672,
        'longitude': 77.2100,
        'is_active': True,
    },
    {
        'name': 'Medanta — The Medicity',
        'address': 'Sector 38, CH Baktawar Singh Road',
        'city': 'Gurugram',
        'state': 'Haryana',
        'phone': '+91 124 441 1441',
        'email': 'contactus@medanta.org',
        'website': 'https://www.medanta.org',
        'specialty': 'Neurosurgery',
        'hospital_type': 'Private',
        'accreditation': 'NABH, JCI',
        'rating': 4.7,
        'facilities': 'Brain Tumor Surgery,Gamma Knife,Neuro ICU,3T MRI,PET-CT,Neuronavigation,Intraoperative Monitoring',
        'doctors': 'Dr. Arun Saroha – Neurosurgeon, Dr. Praveen Gupta – Neurologist',
        'is_mri_center': True,
        'mri_types': '3T MRI, fMRI',
        'cost_range': '₹7000 – ₹16000',
        'latitude': 28.4421,
        'longitude': 77.0454,
        'is_active': True,
    },
]


def seed():
    added = 0
    skipped = 0
    for data in NEW_HOSPITALS:
        exists = Hospital.query.filter_by(name=data['name'], city=data['city']).first()
        if exists:
            skipped += 1
            continue
        h = Hospital(**data)
        db.session.add(h)
        added += 1

    db.session.commit()
    print(f"Done. Added: {added}  |  Skipped (already exist): {skipped}")


if __name__ == '__main__':
    from app import create_app
    app = create_app()
    with app.app_context():
        seed()